### ISSUE TITLE
issues in using dfbvideosink

### ISSUE THREAD

**Issue by saalokk** [yell0wd0g/gst-plugins-bad#2]
#Hi Guys,
I'm getting run time assertion issue using dfbvideosink.
Please help me resolving the same.
I have gstreamer bad plugin version 1.12.0 and DirectFB 1.7.6
ERROR:dfb-example.c:59:main: assertion failed: (sink)
Aborted (core dumped)
Regards,
Alok

**Comment by yell0wd0g** [comment]
I think you wanted to file this issue in the upstream repo https://github.com/GStreamer/gst-plugins-bad :-)
